osx_image: xcode7.3
language: objective-c
install:
- gem install cocoapods -v 0.39.0 --no-document

before_script:
- cd Example
- pod install

xcode_workspace: PopupCollectionViewController.xcworkspace
xcode_scheme: PopupCollectionViewControllerExample
xcode_sdk: iphonesimulator
